import licenses from '../assets/licenses.json';

export interface ThirdPartyLicense {
  name: string;
  version: string;
  license: string;
  repository: string | null;
}

/** Generated by `pnpm licenses:generate` — direct production dependencies only. */
export const THIRD_PARTY_LICENSES: ThirdPartyLicense[] = licenses;

/** Full license texts live in the repository so the app bundle stays small. */
export const THIRD_PARTY_LICENSES_URL =
  'https://github.com/Ahoshinet/subscription-app/blob/main/THIRD_PARTY_LICENSES.md';
